# Module 3 - Scientific Data Manipulation
## 2. Pandas DataFrames

In this notebook, we move from arrays to tables. **Pandas DataFrames** are one of the most important tools for scientific data manipulation in Python.

A DataFrame is similar to a spreadsheet: it has rows, columns, and labels. It is especially useful when measurements come with metadata such as station name, timestamp, or sensor type.

### Learning goals

By the end of this notebook, you should be able to:

- create a DataFrame,
- inspect its structure,
- select rows and columns,
- filter observations,
- sort values,
- create new columns,
- group data and compute simple aggregations.

## 2.1 Importing Pandas and Building a Table

Pandas is commonly imported with the alias `pd`. We will also import NumPy because it is often used together with Pandas.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "station": ["A", "A", "B", "B", "C", "C"],
    "date": ["2026-05-01", "2026-05-02", "2026-05-01", "2026-05-02", "2026-05-01", "2026-05-02"],
    "temperature": [18.4, 19.1, 17.8, 18.3, 20.2, 20.5],
    "humidity": [62, 60, 68, 66, 55, 54],
    "rain_mm": [0.0, 1.2, 3.4, 0.8, 0.0, 0.0]
}

df = pd.DataFrame(data)
df

  station        date  temperature  humidity  rain_mm
0       A  2026-05-01         18.4        62      0.0
1       A  2026-05-02         19.1        60      1.2
2       B  2026-05-01         17.8        68      3.4
3       B  2026-05-02         18.3        66      0.8
4       C  2026-05-01         20.2        55      0.0
5       C  2026-05-02         20.5        54      0.0

Each column contains one variable, and each row represents one observation.

This is a very common structure in research data: one row per sample, one column per feature or measured quantity.

## 2.2 Inspecting Data

Before any analysis, it is useful to inspect the dataset. We usually want to answer basic questions such as:

- What columns are available?
- How many rows do we have?
- Which columns are numeric?
- Are there any missing values?

In [3]:
df.head()

  station        date  temperature  humidity  rain_mm
0       A  2026-05-01         18.4        62      0.0
1       A  2026-05-02         19.1        60      1.2
2       B  2026-05-01         17.8        68      3.4
3       B  2026-05-02         18.3        66      0.8
4       C  2026-05-01         20.2        55      0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   station      6 non-null      object
 1   date         6 non-null      object
 2   temperature  6 non-null      float64
 3   humidity     6 non-null      int64
 4   rain_mm      6 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 372.0+ bytes

In [5]:
df.select_dtypes(include="number").describe()

       temperature   humidity   rain_mm
count     6.000000   6.000000  6.000000
mean     19.050000  60.833333  0.900000
std       1.093161   5.671567  1.325142
min      17.800000  54.000000  0.000000
25%      18.325000  56.250000  0.000000
50%      18.750000  61.000000  0.400000
75%      19.925000  65.000000  1.100000
max      20.500000  68.000000  3.400000

In [6]:
print("Columns:", df.columns.tolist())
print("Shape:", df.shape)

Columns: ['station', 'date', 'temperature', 'humidity', 'rain_mm']
Shape: (6, 5)

## 2.3 Loading Data from a File-like Source

In practice, researchers often load data from CSV files. The example below simulates that process using a text string so that the notebook remains self-contained.

In [7]:
from io import StringIO

csv_text = '''station,date,temperature,humidity,rain_mm
A,2026-05-03,19.4,59,0.0
B,2026-05-03,18.0,67,1.0
C,2026-05-03,20.7,53,0.0
'''

df_csv = pd.read_csv(StringIO(csv_text))
df_csv

  station        date  temperature  humidity  rain_mm
0       A  2026-05-03         19.4        59      0.0
1       B  2026-05-03         18.0        67      1.0
2       C  2026-05-03         20.7        53      0.0

The syntax is the same as when loading a normal CSV file with `pd.read_csv("filename.csv")`.

## 2.4 Selecting Columns and Rows

We can select:

- one column,
- several columns,
- rows by position,
- rows by label or condition.

In [8]:
df["temperature"]

0    18.4
1    19.1
2    17.8
3    18.3
4    20.2
5    20.5
Name: temperature, dtype: float64

In [9]:
df[["station", "temperature", "humidity"]]

  station  temperature  humidity
0       A         18.4        62
1       A         19.1        60
2       B         17.8        68
3       B         18.3        66
4       C         20.2        55
5       C         20.5        54

In [10]:
df.iloc[0:3]

  station        date  temperature  humidity  rain_mm
0       A  2026-05-01         18.4        62      0.0
1       A  2026-05-02         19.1        60      1.2
2       B  2026-05-01         17.8        68      3.4

In [11]:
df.loc[0:2, ["station", "rain_mm"]]

  station  rain_mm
0       A      0.0
1       A      1.2
2       B      3.4

- `iloc` selects by integer position.
- `loc` selects by labels and column names.

For beginners, this distinction is worth learning early because it appears frequently in Pandas code.

## 2.5 Filtering Rows

Filtering keeps only rows that satisfy a condition.

In [12]:
warm_days = df[df["temperature"] > 18.5]
warm_days

  station        date  temperature  humidity  rain_mm
1       A  2026-05-02         19.1        60      1.2
4       C  2026-05-01         20.2        55      0.0
5       C  2026-05-02         20.5        54      0.0

In [13]:
dry_days = df[df["rain_mm"] == 0]
dry_days

  station        date  temperature  humidity  rain_mm
0       A  2026-05-01         18.4        62      0.0
4       C  2026-05-01         20.2        55      0.0
5       C  2026-05-02         20.5        54      0.0

In [14]:
warm_and_dry = df[(df["temperature"] > 18.5) & (df["rain_mm"] == 0)]
warm_and_dry

  station        date  temperature  humidity  rain_mm
4       C  2026-05-01         20.2        55      0.0
5       C  2026-05-02         20.5        54      0.0

This type of filtering is common in environmental data analysis. For example, a researcher may want to inspect only dry days, only high-humidity periods, or only observations from one station.

## 2.6 Sorting Data

Sorting can help us identify the largest or smallest values quickly.

In [15]:
df.sort_values(by="temperature", ascending=False)

  station        date  temperature  humidity  rain_mm
5       C  2026-05-02         20.5        54      0.0
4       C  2026-05-01         20.2        55      0.0
1       A  2026-05-02         19.1        60      1.2
0       A  2026-05-01         18.4        62      0.0
3       B  2026-05-02         18.3        66      0.8
2       B  2026-05-01         17.8        68      3.4

In [16]:
df.sort_values(by=["station", "date"])

  station        date  temperature  humidity  rain_mm
0       A  2026-05-01         18.4        62      0.0
1       A  2026-05-02         19.1        60      1.2
2       B  2026-05-01         17.8        68      3.4
3       B  2026-05-02         18.3        66      0.8
4       C  2026-05-01         20.2        55      0.0
5       C  2026-05-02         20.5        54      0.0

Sorting by multiple columns is useful when we want a logical order, for example station first and date second.

## 2.7 Creating New Columns

A DataFrame becomes more useful when we derive new variables from existing ones.

In [17]:
df["temperature_f"] = df["temperature"] * 9/5 + 32
df["dry_day"] = df["rain_mm"] == 0
df["humidity_fraction"] = df["humidity"] / 100

df

  station        date  temperature  ...  temperature_f  dry_day  humidity_fraction
0       A  2026-05-01         18.4  ...          65.12     True               0.62
1       A  2026-05-02         19.1  ...          66.38    False               0.60
2       B  2026-05-01         17.8  ...          64.04    False               0.68
3       B  2026-05-02         18.3  ...          64.94    False               0.66
4       C  2026-05-01         20.2  ...          68.36     True               0.55
5       C  2026-05-02         20.5  ...          68.90     True               0.54

[6 rows x 8 columns]

These transformations are vectorized, which means they are applied to the whole column at once.

## 2.8 Renaming and Reordering Columns

Researchers often rename columns to make a dataset easier to read or more consistent with later analysis.

In [18]:
renamed = df.rename(columns={"rain_mm": "rainfall_mm"})
renamed = renamed[["station", "date", "temperature", "temperature_f", "humidity", "humidity_fraction", "rainfall_mm", "dry_day"]]
renamed.head()

  station        date  temperature  ...  humidity_fraction  rainfall_mm  dry_day
0       A  2026-05-01         18.4  ...               0.62          0.0     True
1       A  2026-05-02         19.1  ...               0.60          1.2    False
2       B  2026-05-01         17.8  ...               0.68          3.4    False
3       B  2026-05-02         18.3  ...               0.66          0.8    False
4       C  2026-05-01         20.2  ...               0.55          0.0     True

[5 rows x 8 columns]

This step is not always necessary, but it is useful when combining data from different sources that use slightly different column names.

## 2.9 Grouping and Aggregation

A common task is to compute summaries for groups of rows. In environmental data, we may want average measurements per station.

In [19]:
df.groupby("station")["temperature"].mean()

station
A    18.75
B    18.05
C    20.35
Name: temperature, dtype: float64

In [20]:
df.groupby("station")[["temperature", "humidity", "rain_mm"]].mean()

         temperature  humidity  rain_mm
station
A              18.75      61.0      0.6
B              18.05      67.0      2.1
C              20.35      54.5      0.0

In [21]:
summary = df.groupby("station").agg({
    "temperature": ["mean", "max"],
    "humidity": "mean",
    "rain_mm": "sum"
})

summary

        temperature       humidity rain_mm
               mean   max     mean     sum
station
A             18.75  19.1     61.0     1.2
B             18.05  18.3     67.0     4.2
C             20.35  20.5     54.5     0.0

Grouping and aggregation are powerful because they reduce many rows into a smaller summary table.

## 2.10 Guided Practice

Complete the tasks below.

1. Select all observations from station B.
2. Compute the mean humidity for each station.
3. Create a new column called `hot_day` for temperatures above 20°C.
4. Sort the table by humidity from highest to lowest.

In [22]:
station_b = ...
mean_humidity = ...
practice_df = df.copy()
practice_df["hot_day"] = ...
sorted_by_humidity = ...

print("Station B:")
display(station_b)

print("Mean humidity by station:")
print(mean_humidity)

print("Updated DataFrame:")
display(practice_df)

print("Sorted by humidity:")
display(sorted_by_humidity)

Station B:

Ellipsis

Mean humidity by station:
Ellipsis
Updated DataFrame:

  station        date  temperature  ...  dry_day  humidity_fraction   hot_day
0       A  2026-05-01         18.4  ...     True               0.62  Ellipsis
1       A  2026-05-02         19.1  ...    False               0.60  Ellipsis
2       B  2026-05-01         17.8  ...    False               0.68  Ellipsis
3       B  2026-05-02         18.3  ...    False               0.66  Ellipsis
4       C  2026-05-01         20.2  ...     True               0.55  Ellipsis
5       C  2026-05-02         20.5  ...     True               0.54  Ellipsis

[6 rows x 9 columns]

Sorted by humidity:

Ellipsis

### Suggested solution

In [23]:
station_b = df[df["station"] == "B"]
mean_humidity = df.groupby("station")["humidity"].mean()
practice_df = df.copy()
practice_df["hot_day"] = practice_df["temperature"] > 20
sorted_by_humidity = practice_df.sort_values(by="humidity", ascending=False)

print("Station B:")
display(station_b)

print("Mean humidity by station:")
print(mean_humidity)

print("Updated DataFrame:")
display(practice_df)

print("Sorted by humidity:")
display(sorted_by_humidity)

Station B:

  station        date  temperature  ...  temperature_f  dry_day  humidity_fraction
2       B  2026-05-01         17.8  ...          64.04    False               0.68
3       B  2026-05-02         18.3  ...          64.94    False               0.66

[2 rows x 8 columns]

Mean humidity by station:
station
A    61.0
B    67.0
C    54.5
Name: humidity, dtype: float64
Updated DataFrame:

  station        date  temperature  ...  dry_day  humidity_fraction  hot_day
0       A  2026-05-01         18.4  ...     True               0.62    False
1       A  2026-05-02         19.1  ...    False               0.60    False
2       B  2026-05-01         17.8  ...    False               0.68    False
3       B  2026-05-02         18.3  ...    False               0.66    False
4       C  2026-05-01         20.2  ...     True               0.55     True
5       C  2026-05-02         20.5  ...     True               0.54     True

[6 rows x 9 columns]

Sorted by humidity:

  station        date  temperature  ...  dry_day  humidity_fraction  hot_day
2       B  2026-05-01         17.8  ...    False               0.68    False
3       B  2026-05-02         18.3  ...    False               0.66    False
0       A  2026-05-01         18.4  ...     True               0.62    False
1       A  2026-05-02         19.1  ...    False               0.60    False
4       C  2026-05-01         20.2  ...     True               0.55     True
5       C  2026-05-02         20.5  ...     True               0.54     True

[6 rows x 9 columns]

## 2.11 Summary

In this notebook, you learned how to:

- create a Pandas DataFrame,
- inspect its structure and contents,
- load CSV-style tabular data,
- select rows and columns,
- filter and sort observations,
- create new derived columns,
- rename and reorder columns,
- group data and compute aggregations.

In the next notebook, we focus on one of the most important real-world problems in data preparation: **missing data**.